DROP TABLE IF EXISTS DailySummary;
CREATE TABLE DailySummary
(
  id                                        INTEGER PRIMARY KEY   AUTOINCREMENT,
  tid                                       VARCHAR(100),
  report_date                               VARCHAR(100),
  mandiri_topup_freq                        BIGINT DEFAULT 0,
  mandiri_topup_revenue                     BIGINT DEFAULT 0,
  mandiri_shop_freq                         BIGINT DEFAULT 0,
  mandiri_shop_revenue                      BIGINT DEFAULT 0,
  mandiri_deposit_refill_count              BIGINT DEFAULT 0,
  mandiri_deposit_refill_amount             BIGINT DEFAULT 0,
  mandiri_deposit_last_balance              BIGINT DEFAULT 0,
  mandiri_transaction_count                 BIGINT DEFAULT 0,
  mandiri_transaction_amount                BIGINT DEFAULT 0,
  mandiri_card_trx_count                    BIGINT DEFAULT 0,
  mandiri_card_trx_amount                   BIGINT DEFAULT 0,
  bni_topup_freq                            BIGINT DEFAULT 0,
  bni_topup_revenue                         BIGINT DEFAULT 0,
  bni_shop_freq                             BIGINT DEFAULT 0,
  bni_shop_revenue                          BIGINT DEFAULT 0,
  bni_deposit_refill_count                  BIGINT DEFAULT 0,
  bni_deposit_refill_amount                 BIGINT DEFAULT 0,
  bni_deposit_last_balance                  BIGINT DEFAULT 0,
  bni_transaction_count                     BIGINT DEFAULT 0,
  bni_transaction_amount                    BIGINT DEFAULT 0,
  bni_card_trx_count                        BIGINT DEFAULT 0,
  bni_card_trx_amount                       BIGINT DEFAULT 0,
  bri_topup_freq                            BIGINT DEFAULT 0,
  bri_topup_revenue                         BIGINT DEFAULT 0,
  bri_shop_freq                             BIGINT DEFAULT 0,
  bri_shop_revenue                          BIGINT DEFAULT 0,
  bri_transaction_count                     BIGINT DEFAULT 0,
  bri_transaction_amount                    BIGINT DEFAULT 0,
  bri_card_trx_count                        BIGINT DEFAULT 0,
  bri_card_trx_amount                       BIGINT DEFAULT 0,
  bca_topup_freq                            BIGINT DEFAULT 0,
  bca_topup_revenue                         BIGINT DEFAULT 0,
  bca_shop_freq                             BIGINT DEFAULT 0,
  bca_shop_revenue                          BIGINT DEFAULT 0,
  bca_transaction_count                     BIGINT DEFAULT 0,
  bca_transaction_amount                    BIGINT DEFAULT 0,
  bca_card_trx_count                        BIGINT DEFAULT 0,
  bca_card_trx_amount                       BIGINT DEFAULT 0,
  dki_topup_freq                            BIGINT DEFAULT 0,
  dki_topup_revenue                         BIGINT DEFAULT 0,
  dki_shop_freq                             BIGINT DEFAULT 0,
  dki_shop_revenue                          BIGINT DEFAULT 0,
  dki_transaction_count                     BIGINT DEFAULT 0,
  dki_transaction_amount                    BIGINT DEFAULT 0,
  dki_card_trx_count                        BIGINT DEFAULT 0,
  dki_card_trx_amount                       BIGINT DEFAULT 0,
  created_at                                TEXT DEFAULT CURRENT_TIMESTAMP,
  synced_at                                 TEXT
);